allowed-duplicate-crates = [
  'regex-automata',
  'regex-syntax',
  'block-sys',
  'bitflags',
  'block2',
  'event-listener',
  'libloading',
  'objc-sys',
  'objc2',
  'objc2-encode',
  'redox_syscall',
  'syn',
  'tracing-log',
  'windows',
  'windows-core',
  'windows-implement',
  'windows-interface',
  'windows-sys',
  'windows-targets',
  'windows_aarch64_gnullvm',
  'windows_aarch64_msvc',
  'windows_i686_gnu',
  'windows_i686_msvc',
  'windows_x86_64_gnu',
  'windows_x86_64_gnullvm',
  'windows_x86_64_msvc',
]
