[package]
name = "viz"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
clap.workspace = true
eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
bevy.workspace = true

[lints]
workspace = true
