name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    # Use v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    # https://www.uffizzi.com/blog/optimizing-rust-builds-for-faster-github-actions-pipelines
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4
    - uses: actions/checkout@v4
     - uses: actions-rs/toolchain@v1
            with:
                toolchain: 1.78.0
                components: clippy, rustfmt
                override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace
        name: Lints
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --workspace -- -A warnings -W clippy::pedantic -W clippy::perf
        name: Nits

