name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
    # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
    # Use v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: taiki-e/install-action@nextest
    # https://www.uffizzi.com/blog/optimizing-rust-builds-for-faster-github-actions-pipelines
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.4
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
          components: clippy, rustfmt
    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo nextest run
    - uses: clechasseur/rs-clippy-check@v3
      with:
        args: --workspace

